export const AFFIRMATIONS: string[] = [
  'Je mérite le repos et la douceur, sans avoir à les justifier.',
  'Mes émotions sont valides, même quand elles sont inconfortables.',
  "Je fais de mon mieux avec ce que j'ai aujourd'hui, et c'est suffisant.",
  'Je peux poser mes limites sans culpabilité.',
  "Chaque jour, je progresse à mon propre rythme.",
  'Je suis capable de traverser des moments difficiles.',
  "Ma valeur ne dépend pas de ma productivité.",
  "J'accueille mes imperfections comme une part de mon humanité.",
  'Je choisis de me parler avec la même bienveillance que je réserve aux autres.',
  "Je peux recommencer, autant de fois que nécessaire.",
  'Ce que je ressens ne définit pas qui je suis.',
  "Je fais de la place pour le calme dans ma journée.",
  'Je suis digne d\'amour, tel·le que je suis en ce moment.',
  "Il est normal de ne pas tout savoir gérer seul·e.",
  'Je respire, et cela suffit pour cet instant.',
  "Je célèbre mes petites victoires, elles comptent.",
  'Ma santé mentale est une priorité légitime.',
  "Je lâche ce que je ne peux pas contrôler.",
  'Je suis en train de devenir la meilleure version de moi-même.',
  "Aujourd'hui, je choisis la douceur envers moi-même.",
];
